# Generated by Django 4.1.3 on 2022-12-07 18:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('prenom', models.CharField(max_length=70)),
                ('classement', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ligue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=0, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='match', max_length=70)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 12, 7, 18, 2, 16, 905332, tzinfo=datetime.timezone.utc), verbose_name='date du match')),
                ('score', models.IntegerField(default=0)),
                ('ligue', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game.ligue')),
            ],
        ),
    ]
