# Generated by Django 4.1.3 on 2022-12-07 18:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='locaux',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='game.equipe'),
        ),
        migrations.AlterField(
            model_name='ligue',
            name='nom',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 18, 38, 27, 230859, tzinfo=datetime.timezone.utc), verbose_name='date du match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='ligue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='game.ligue'),
        ),
    ]
