# Generated by Django 4.1.3 on 2022-12-08 08:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_match_locaux_alter_ligue_nom_alter_match_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='visiteur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='visiteur', to='game.equipe'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 8, 11, 9, 493056, tzinfo=datetime.timezone.utc), verbose_name='date du match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='locaux',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='locaux', to='game.equipe'),
        ),
    ]
