# Generated by Django 4.1.3 on 2022-12-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_match_score_locaux_alter_match_score_visiteurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score_locaux',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_visiteurs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
