# Generated by Django 4.1.3 on 2022-12-08 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_match_visiteur_alter_match_date_alter_match_locaux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 8, 19, 7, 370746, tzinfo=datetime.timezone.utc), verbose_name='date du match'),
        ),
    ]
