# Generated by Django 4.1.3 on 2022-12-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_match_score_locaux_alter_match_score_visiteurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='score2',
            field=models.IntegerField(default=0),
        ),
    ]
