# Generated by Django 4.1.3 on 2022-12-08 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_match_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 8, 8, 11, 9, 493056, tzinfo=datetime.timezone.utc), verbose_name='date du match'),
        ),
    ]
