# Generated by Django 4.1.3 on 2022-12-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_equipe_prenom_alter_match_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.CharField(default='0-0', max_length=5),
        ),
    ]
