# Generated by Django 4.1.3 on 2022-12-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_match_score_match_score_locaux_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='classement',
        ),
    ]
