# Generated by Django 4.1.3 on 2022-12-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_equipe_classement'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='ligues',
            field=models.ManyToManyField(to='game.ligue'),
        ),
    ]
