# Generated by Django 4.1.3 on 2022-12-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_equipe_ligues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='nom',
            field=models.CharField(default='', max_length=70),
        ),
    ]
